version: '3.8'
services:
  # redis:
  #   container_name: redis
  #   image: redis:3
      
  user-microservice:
    container_name: user-microservice
    image: user-microservice:v1
    restart: always
    ports:
      - ${MICROSERVICE_USER_PORT}:${MICROSERVICE_USER_PORT}
    env_file:
      - .env
    # depends_on:
    #   - redis

  task-microservice:
    container_name: task-microservice
    image: task-microservice:v1
    restart: always
    ports:
      - ${MICROSERVICE_TASK_PORT}:${MICROSERVICE_TASK_PORT}
    env_file:
      - .env